version: "2"
services:  

  zookeeper:
    image: landoop/fast-data-dev
    ports:
      - "2181:2181"
    mem_limit: 1024m
    environment:
      - "JAVA_OPTS=-XX:+UnlockExperimentalVMOptions"
      - "JAVA_OPTS=-XX:+UseCGroupMemoryLimitForHeap"
    network_mode: "host"
    container_name: zookeeper
    hostname: localhost
    restart: always


  kafka:
    image: landoop/fast-data-dev
    ports:
      - "9092:9092"
    container_name: kafka
    mem_limit: 1500m
    environment:
      JAVA_OPTS: "-XX:+UnlockExperimentalVMOptions
                  -XX:+UseCGroupMemoryLimitForHeap"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
      KAFKA_CREATE_TOPICS: "Kafka_Example"
    hostname: localhost
    depends_on:
     - zookeeper
    restart: always

