version: "2.1"
services:
  mysql:
    image: mysql:5.7
    ports:
    - 3306:3306
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_PASSWORD: root
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
    - /opt/datasql:/var/lib/mysql
    network_mode: "host"
    hostname: localhost
    restart: always
    healthcheck:
      test: "exit 0"
